src/Entity/Event.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

#[Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[Column, Id, GeneratedValue(strategy: 'SEQUENCE')]
    private ?int $id = null;

    #[Column]
    private string $name = '';

    #[Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $date_start = null;

    #[Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $date_end = null;

    #[Column(nullable: true)]
    private ?string $event_type = null;

    #[Column(nullable: true)]
    private ?string $recurring = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getEventType(): ?string
    {
        return $this->event_type;
    }

    public function setEventType(?string $Event_type): self
    {
        $this->event_type = $Event_type;

        return $this;
    }

    public function getRecurring(): ?string
    {
        return $this->recurring;
    }

    public function setRecurring(?string $recurring): self
    {
        $this->recurring = $recurring;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @extends AbstractType<Event>
 */
class EventType extends AbstractType
{
    public function buildForm(
        FormBuilderInterface $builder,
        array $options
    ): void {
        $builder
            ->add('name')
            ->add(
                'eventType',
                ChoiceType::class,
                [
                    'choices' => [
                        'AP'           => 'ap',
                        'Hacker'       => 'hacker',
                        'Builder'      => 'builder',
                        'Trekker'      => 'trekker',
                        'Purifier'     => 'purifier',
                        'Recharger'    => 'recharger',
                        'OPR'          => 'recon',
                        'Fields/Links' => 'fieldslinks',
                    ],
                ]
            )
            ->add('date_start')
            ->add('date_end');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => Event::class,
            ]
        );
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\AgentStatRepository;
use App\Repository\EventRepository;
use App\Service\EventHelper;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class EventController extends BaseController
{
    public function __construct(
        private readonly EventRepository $eventRepository,
        private readonly AgentStatRepository $statRepository,
        private readonly EventHelper $eventHelper
    ) {
    }

    #[Route(path: '/event/', name: 'event_index', methods: ['GET'])]
    #[IsGranted('ROLE_AGENT')]
    public function index(): Response
    {
        return $this->render(
            'event/index.html.twig',
            [
                'events' => $this->eventRepository->findAll(),
            ]
        );
    }

    #[Route(path: '/event/new', name: 'event_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render(
            'event/new.html.twig',
            [
                'event' => $event,
                'form'  => $form,
            ]
        );
    }

    #[Route(path: '/event/{id}', name: 'event_show', methods: ['GET'])]
    #[IsGranted('ROLE_AGENT')]
    public function show(Event $event): Response
    {
        $entries = $this->statRepository->findByDate(
            $event->getDateStart(),
            $event->getDateEnd()
        );
        $values = $this->eventHelper->calculateResults($event, $entries);
        $now = new DateTime();
        if ($event->getDateStart() > $now) {
            $status = 'future';
        } elseif ($event->getDateEnd() < $now) {
            $status = 'past';
        } else {
            $status = 'current';
        }

        return $this->render(
            'event/show.html.twig',
            [
                'event' => $event,
                'values' => $values,
                'status' => $status,
            ]
        );
    }

    #[Route(path: '/event/{id}/edit', name: 'event_edit', methods: [
        'GET',
        'POST',
    ])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(
        Request $request,
        Event $event,
        EntityManagerInterface $entityManager
    ): Response {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render(
            'event/edit.html.twig',
            [
                'event' => $event,
                'form'  => $form,
            ]
        );
    }

    #[Route(path: '/event/{id}', name: 'event_delete', methods: ['DELETE'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(
        Request $request,
        Event $event,
        EntityManagerInterface $entityManager
    ): Response {
        if ($this->isCsrfTokenValid(
            'delete'.$event->getId(),
            (string)$request->request->get('_token')
        )
        ) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}"
      onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/calendar.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Calendar
{% endblock %}

{% block body %}
    <div {{ stimulus_controller('calendar', {
        'eventsUrl':path('fc_load_events'),
        'defaultTimeZone':defaultTimeZone(),
    }) }}>

        <label for="time-zone-selector">Timezone:</label>
        <select id="time-zone-selector" {{ stimulus_target('calendar','timeZoneSelector') }}>
            <option value="local" selected>local</option>
            <option value="UTC">UTC</option>
        </select>
        <div {{ stimulus_target('calendar', 'frame') }}></div>
    </div>
{% endblock %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <h1>Event index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Type</th>
            <th>Date_start</th>
            <th>Date_end</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td><a href="{{ path('event_show', {'id': event.id}) }}">{{ event.name }}</a></td>
                <td>{{ event.eventType }}</td>
                <td>{{ event.dateStart ? event.dateStart|date('Y-m-d H:i') : '' }}</td>
                <td>{{ event.dateEnd ? event.dateEnd|date('Y-m-d H:i') : '' }}</td>
                <td>
                    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('event_new') }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}4E Events - {{ event.name }}{% endblock %}
{% block og_description %}4E Events - {{ event.name }}{% endblock %}

{% block body %}

    <h1>{{ event.name }}</h1>

    {{ 'Event type: {type}'|trans({'type': event.eventType}) }}

    <h4>
        <span class="oi oi-media-play"></span> {{ event.dateStart ? event.dateStart|date('Y-m-d H:i') : '' }}<br>
        <span class="oi oi-media-stop"></span> {{ event.dateEnd ? event.dateEnd|date('Y-m-d H:i') : '' }}
    </h4>
    {% if 'past' == status %}
        <h4>{{ 'Final results'|trans }}</h4>
    {% else %}
        <div class="text-center alert alert-warning"
                {{ stimulus_controller('clock-counter', {
                    deadline: 'current' == status ? event.dateEnd|date('Y-m-d H:i') : event.dateStart|date('Y-m-d H:i', false)
                }) }}>
            {% if 'current' == status %}
                <b>{{ 'The event ends in'|trans }}</b>
            {% else %}
                <b>{{ 'The event starts in'|trans }}</b>
            {% endif %}
            {{ 'Days:'|trans }} <b data-clock-counter-target="days"></b><br>
            {{ 'Hours:'|trans }} <b data-clock-counter-target="hours"></b>
            {{ 'Minutes:'|trans }} <b data-clock-counter-target="minutes"></b>
            {{ 'Seconds:'|trans }} <b data-clock-counter-target="seconds"></b>
        </div>
    {% endif %}

    {% if values %}
        <table>
            {% set cnt = 1 %}
            {% for name, value in values %}
                {% if cnt == 1 %}
                    {% set img = '<img src="'~asset('images/medals/1st-place-medal_36.png')~'" style="height: 36px">' %}
                {% elseif cnt == 2 %}
                    {% set img = '<img src="'~asset('images/medals/2nd-place-medal_36.png')~'" style="height: 36px">' %}
                {% elseif cnt == 3 %}
                    {% set img = '<img src="'~asset('images/medals/3rd-place-medal_36.png')~'" style="height: 36px">' %}
                {% else %}
                    {% set img = '' %}
                {% endif %}
                <tr>
                    <th>{{ img|raw }}{{ cnt ~ '. ' ~name|raw }}</th>
                    <td class="text-right">
                        {% if 'fieldslinks' == event.eventType %}
                            {{ value|number_format(2, '.', ',') }}
                        {% else %}
                            {{ value|number_format }}
                        {% endif %}
                    </td>
                </tr>
                {% set cnt = cnt + 1 %}
            {% endfor %}
        </table>
    {% else %}
        {% if 'future' == status %}
        {% else %}
            No hay estadisticas para este evento :(
        {% endif %}
    {% endif %}
{% endblock %}