src/Entity/Agent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Stringable;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\AgentRepository;

#[Entity(repositoryClass: AgentRepository::class)]
class Agent implements Stringable
{
    #[Column, Id, GeneratedValue(strategy: 'SEQUENCE')]
    protected ?int $id = null;

    #[Column]
    #[Assert\NotBlank]
    protected string $nickname = '';

    #[Column(nullable: true)]
    private ?string $realName = '';

    #[Column(type: 'decimal', precision: 10, scale: 6, nullable: true)]
    private ?string $lat = null;

    #[Column(type: 'decimal', precision: 10, scale: 6, nullable: true)]
    private ?string $lon = null;

    #[ManyToOne]
    #[JoinColumn(nullable: false)]
    private ?Faction $faction = null;

    /**
     * @var Collection<int, Comment>
     */
    #[OneToMany(targetEntity: Comment::class, mappedBy: 'agent')]
    private Collection $comments;

    #[Column(type: Types::TEXT, nullable: true)]
    private ?string $custom_medals = '';

    #[ManyToOne(inversedBy: 'agents')]
    private ?MapGroup $map_group = null;

    #[Column(nullable: true)]
    private ?string $telegram_name = '';

    #[Column(nullable: true)]
    private ?int $telegram_id = null;

    #[Column(length: 48, nullable: true)]
    private ?string $telegram_connection_secret = null;

    #[Column(nullable: true)]
    private ?bool $hasNotifyUploadStats = null;

    #[Column(nullable: true)]
    private ?bool $hasNotifyEvents = null;

    #[Column(nullable: true)]
    private ?bool $hasNotifyStatsResult = null;

    #[Column(length: 2, nullable: true)]
    private ?string $locale = '';

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNickname(): string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getRealName(): ?string
    {
        return $this->realName;
    }

    public function setRealName(?string $realName): self
    {
        $this->realName = $realName;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(string $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLon(): ?string
    {
        return $this->lon;
    }

    public function setLon(string $lon): self
    {
        $this->lon = $lon;

        return $this;
    }

    public function getFaction(): ?Faction
    {
        return $this->faction;
    }

    public function setFaction(?Faction $faction): self
    {
        $this->faction = $faction;

        return $this;
    }

    public function __toString(): string
    {
        return $this->nickname;
    }

    public function __sleep(): array
    {
        return ['id'];
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAgent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAgent() === $this) {
                $comment->setAgent(null);
            }
        }

        return $this;
    }

    public function getCustomMedals(): ?string
    {
        return $this->custom_medals;
    }

    public function setCustomMedals(?string $custom_medals): self
    {
        $this->custom_medals = $custom_medals;

        return $this;
    }

    public function getMapGroup(): ?MapGroup
    {
        return $this->map_group;
    }

    public function setMapGroup(?MapGroup $map_group): self
    {
        $this->map_group = $map_group;

        return $this;
    }

    public function getTelegramName(): ?string
    {
        return $this->telegram_name;
    }

    public function setTelegramName(?string $telegram_name): self
    {
        $this->telegram_name = $telegram_name;

        return $this;
    }

    public function getTelegramId(): ?int
    {
        return $this->telegram_id;
    }

    public function setTelegramId(?int $telegram_id): self
    {
        $this->telegram_id = $telegram_id;

        return $this;
    }

    public function getTelegramConnectionSecret(): ?string
    {
        return $this->telegram_connection_secret;
    }

    public function setTelegramConnectionSecret(
        ?string $telegram_connection_secret
    ): self {
        $this->telegram_connection_secret = $telegram_connection_secret;

        return $this;
    }

    public function getHasNotifyUploadStats(): ?bool
    {
        return $this->hasNotifyUploadStats;
    }

    public function setHasNotifyUploadStats(?bool $hasNotifyUploadStats): self
    {
        $this->hasNotifyUploadStats = $hasNotifyUploadStats;

        return $this;
    }

    public function getHasNotifyEvents(): ?bool
    {
        return $this->hasNotifyEvents;
    }

    public function setHasNotifyEvents(?bool $hasNotifyEvents): self
    {
        $this->hasNotifyEvents = $hasNotifyEvents;

        return $this;
    }

    public function getHasNotifyStatsResult(): ?bool
    {
        return $this->hasNotifyStatsResult;
    }

    public function setHasNotifyStatsResult(?bool $hasNotifyStatsResult): self
    {
        $this->hasNotifyStatsResult = $hasNotifyStatsResult;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use App\Repository\EventRepository;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;

#[Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[Column, Id, GeneratedValue(strategy: 'SEQUENCE')]
    private ?int $id = null;

    #[Column]
    private string $name = '';

    #[Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $date_start = null;

    #[Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $date_end = null;

    #[Column(nullable: true)]
    private ?string $event_type = null;

    #[Column(nullable: true)]
    private ?string $recurring = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getEventType(): ?string
    {
        return $this->event_type;
    }

    public function setEventType(?string $Event_type): self
    {
        $this->event_type = $Event_type;

        return $this;
    }

    public function getRecurring(): ?string
    {
        return $this->recurring;
    }

    public function setRecurring(?string $recurring): self
    {
        $this->recurring = $recurring;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\OneToOne;
use Doctrine\ORM\Mapping\Table;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\UserRepository;

#[Entity(repositoryClass: UserRepository::class)]
#[Table(name: 'agent_user')]
#[UniqueEntity(fields: 'email', message: 'This email is already in use')]
class User implements UserInterface, \Stringable
{
    #[Column, Id, GeneratedValue(strategy: 'SEQUENCE')]
    private ?int $id = null;

    /**
     * @var array<string>
     */
    #[Column(type: Types::JSON)]
    private array $roles = [];

    #[Column(unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private string $email = '';

    #[OneToOne(cascade: ['persist', 'remove'])]
    private ?Agent $agent = null;

    #[Column(length: 100, nullable: true)]
    private ?string $googleId = null;

    #[Column(nullable: true)]
    private ?string $fireBaseToken = null;

    #[Column(nullable: true)]
    private ?string $apiToken = '';

    #[Column(nullable: true)]
    private ?string $avatar = null;

    #[Column(type: Types::TEXT, nullable: true)]
    private ?string $avatarEncoded = null;

    public function __toString(): string
    {
        return $this->email;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @return array<string>
     */
    public function hasRole(): array
    {
        return $this->getRoles();
    }

    /**
     * @param array<string> $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPassword(): ?string
    {
        return null;
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getUserAgentName(): string
    {
        if ($this->agent instanceof \App\Entity\Agent) {
            return sprintf(
                '%s <%s>',
                $this->agent->getNickname(),
                $this->email
            );
        }

        return $this->email;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAgent(): ?Agent
    {
        return $this->agent;
    }

    public function setAgent(?Agent $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }

    public function getFireBaseToken(): ?string
    {
        return $this->fireBaseToken;
    }

    public function setFireBaseToken(?string $fireBaseToken): self
    {
        $this->fireBaseToken = $fireBaseToken;

        return $this;
    }

    public function getApiToken(): ?string
    {
        return $this->apiToken;
    }

    public function setApiToken(?string $apiToken): self
    {
        $this->apiToken = $apiToken;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getAvatarEncoded(): ?string
    {
        return $this->avatarEncoded;
    }

    public function setAvatarEncoded(?string $avatarEncoded): self
    {
        $this->avatarEncoded = $avatarEncoded;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\AgentRepository;
use App\Repository\ChallengeRepository;
use App\Repository\CommentRepository;
use App\Repository\IngressEventRepository;
use App\Service\CalendarHelper;
use App\Service\CiteService;
use App\Service\DateTimeHelper;
use App\Service\EventHelper;
use App\Service\MarkdownHelper;
use DateTime;
use DateTimeZone;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class DefaultController extends AbstractController
{
    public function __construct(
        private readonly AgentRepository $agentRepository,
        private readonly CommentRepository $commentRepository,
        private readonly IngressEventRepository $ingressEventRepository,
        private readonly ChallengeRepository $challengeRepository,
        private readonly DateTimeHelper $dateTimeHelper,
        private readonly MarkdownHelper $markdownHelper,
        private readonly CiteService $citeService,
        private readonly CalendarHelper $calendarHelper,
        private readonly EventHelper $eventHelper
    ) {
    }

    #[Route(path: '/', name: 'default', methods: ['GET'], schemes: ['https'])]
    public function index(
        #[Autowire('%env(DEFAULT_TIMEZONE)%')] string $defaultTimeZone,
    ): Response {
        $this->calendarHelper->getEvents();
        $comments = [];
        $currentEvents = [];
        $pastEvents = [];
        $futureEvents = [];
        $ingressFS = [];
        $ingressMD = [];
        $challenges = [];
        $tz = new DateTimeZone($defaultTimeZone);
        $now = new DateTime('now', $tz);
        $now2 = new DateTime();
        if ($this->isGranted('ROLE_AGENT')) {
            $comments = $this->commentRepository->findLatest(5);

            foreach ($comments as $comment) {
                $comment->setText(
                    $this->markdownHelper->parse($comment->getText())
                );
            }

            $pastEvents = $this->eventHelper->getEventsInSpan('past');
            $currentEvents = $this->eventHelper->getEventsInSpan('present');
            $futureEvents = $this->eventHelper->getEventsInSpan('future');

            $ingressFS = $this->ingressEventRepository->findFutureFS();
            $ingressMD = $this->ingressEventRepository->findFutureMD();
            $challenges = $this->challengeRepository->findCurrent();
        }

        return $this->render(
            'default/index.html.twig',
            [
                'now'            => $now,
                'now2'           => $now2,
                'agents'         => $this->agentRepository->findAll(),
                'latestComments' => $comments,
                'pastEvents'     => $pastEvents,
                'currentEvents'  => $currentEvents,
                'futureEvents'   => $futureEvents,
                'ingressFS'      => $ingressFS,
                'ingressMD'      => $ingressMD,
                'nextFs'         => $this->dateTimeHelper->getNextFS(),
                'challenges'     => $challenges,
                'cite'           => $this->citeService->getRandomCite(),
            ]
        );
    }

    #[Route(path: '/calendar', name: 'event_calendar', methods: ['GET'])]
    public function calendar(): Response
    {
        return $this->render('event/calendar.html.twig');
    }

    #[Route(path: '/events', name: 'default_events', methods: ['GET'])]
    #[IsGranted('ROLE_AGENT')]
    public function events(): Response
    {
        return $this->render(
            'default/events.html.twig',
            [
                'ingressFS'         =>
                    $this->ingressEventRepository->findFutureFS(),
                'ingressMD'         =>
                    $this->ingressEventRepository->findFutureMD(),
                'pastEvents'        =>
                    $this->eventHelper->getEventsInSpan('past'),
                'currentEvents'     =>
                    $this->eventHelper->getEventsInSpan('present'),
                'futureEvents'      =>
                    $this->eventHelper->getEventsInSpan('future'),
                'pastChallenges'    =>
                    $this->eventHelper->getChallengesInSpan('past'),
                'currentChallenges' =>
                    $this->eventHelper->getChallengesInSpan('present'),
                'futureChallenges'  =>
                    $this->eventHelper->getChallengesInSpan('future'),
            ]
        );
    }

    #[Route(path: '/privacy', name: 'app_privacy', methods: ['GET'])]
    public function privacy(): Response
    {
        return $this->render('default/privacy.html.twig');
    }
}

templates/default/_comment_list.html.twig
<h3>{{ 'Latest comments'|trans }}</h3>

{% for comment in latestComments %}
    <div class="card">
        <div class="card-header">
            {% if comment.commenter.agent %}
                {{ comment.commenter.agent.nickname }}
                -
            {% endif %}
            {{ comment.datetime|ago }}
        </div>
        <div class="card-body">
            <h5 class="card-title">
                <img src="{{ asset('images/logos/'~comment.agent.faction.name~'.svg') }}"
                     style="height: 32px" alt="logo">
                <a class="{{ comment.agent.faction.name }}"
                   href="{{ path('agent_show', {'id':comment.agent.id}) }}">{{ comment.agent.nickname }}</a>
            </h5>
            <p class="card-text">
                {{ comment.text|raw }}
            </p>
        </div>
    </div>
{% endfor %}

templates/default/_event_list.html.twig
{% if ingressMD %}
    {% for md in ingressMD %}
        <div class="card">
            <div class="card-header">
                <h3>{{ 'Ingress Mission Day'|trans }}</h3>
                <h4><a href="{{ path('ingress_event_public_show', { 'id':md.id }) }}">{{ md.name }}</a></h4>
                {{ md.dateStart|ago }}
            </div>
            <div class="card-body">
                {{ md.description }}
            </div>
            <div class="card-footer">
                <a href="{{ md.link }}">Info</a>
            </div>
        </div>
    {% endfor %}
{% endif %}

{% if ingressFS %}
    <div class="card">
        <div class="card-header">
            <h3>{{ 'Ingress First Saturday'|trans }}</h3>
            {{ nextFs|formatIntlDate }}
        </div>
        <div class="card-body">
            &bull;
            {% for fs in ingressFS %}
                <a href="{{ fs.link }}">{{ fs.name }}</a> &bull;
            {% endfor %}
        </div>
    </div>
{% endif %}

{% for event in currentEvents %}
    <div class="card">
        <div class="card-body">
            <h4>
                <a href="{{ path('event_show', {'id': event.id}) }}">{{ event.name }}</a>
            </h4>

            <div class="text-center alert alert-warning" {{ stimulus_controller('clock-counter', {
                deadline: event.dateEnd|date('Y-m-d H:i', false)
            }) }}>
                <b>{{ 'Ends in'|trans }}</b> -
                {{ 'Days:'|trans }} <b data-clock-counter-target="days"></b>
                {{ 'Hours:'|trans }} <b data-clock-counter-target="hours"></b>:<b data-clock-counter-target="minutes"
                ></b>:<b data-clock-counter-target="seconds"></b>
            </div>

        </div>
    </div>
{% endfor %}

{% for challenge in challenges %}
    <div class="card">
        <div class="card-body">
            <h4>
                <a href="{{ path('challenge_show', {'id': challenge.id}) }}">{{ challenge.name }}</a>
            </h4>

            <div class="text-center alert alert-warning" {{ stimulus_controller('clock-counter', {
                deadline: challenge.dateEnd|date('Y-m-d H:i', false)
            }) }}>
                <b>{{ 'Ends in'|trans }}</b> -
                {{ 'Days:'|trans }} <b data-clock-counter-target="days"></b>
                {{ 'Hours:'|trans }} <b data-clock-counter-target="hours"></b>:<b data-clock-counter-target="minutes"
                ></b>:<b data-clock-counter-target="seconds"></b>
            </div>

        </div>
    </div>
{% endfor %}

{% for event in futureEvents %}
    <div class="card">
        <div class="card-body">
            <h4>
                <a href="{{ path('event_show', {'id': event.id}) }}">{{ event.name }}</a>
            </h4>

            {{ 'Event type: {type}'|trans({'type': event.eventType}) }}

            <div {{ stimulus_controller('clock-counter', {
                deadline: event.dateStart|date('Y-m-d H:i', false)
            }) }}>
                <b>{{ 'The event starts in'|trans }}</b>
                {{ 'Days:'|trans }} <b data-clock-counter-target="days"></b><br>
                {{ 'Hours:'|trans }} <b data-clock-counter-target="hours"></b>
                {{ 'Minutes:'|trans }} <b data-clock-counter-target="minutes"></b>
                {{ 'Seconds:'|trans }} <b data-clock-counter-target="seconds"></b>
            </div>

        </div>
    </div>
{% endfor %}

templates/default/_greeting.html.twig
<h1>{{ 'Welcome!'|trans }}
    {% if is_granted('ROLE_AGENT') %}
        <img src="{{ asset('images/logos/ENL.svg') }}" style="height: 64px" alt="ENL logo">
    {% else %}
        ✅
    {% endif %}
</h1>
{% if is_granted('ROLE_ADMIN') %}
    Hello admin <code>{{ app.user.agent ? app.user.agent.nickname : app.user.username }}</code>
{% elseif is_granted('ROLE_EDITOR') %}
    Bienvenido agente editor <code>{{ app.user.agent ? app.user.agent.nickname : app.user.username }}</code>
{% elseif is_granted('ROLE_INTRO_AGENT') %}
    Bienvenido agente <code>{{ app.user.agent ? app.user.agent.nickname : app.user.username }}</code>
{% elseif app.user %}
    <div class="alert alert-warning">
        Agente 4E, ¡tu cuenta todavía no ha sido activada!<br>
        Pero, ten calma.<br>
        Por favor, comunícate por Telegram con un administrador <a href="https://t.me/GIOBOTNOVICE">@GIOBOTNOVICE</a>
        o <a href="https://t.me/nikp3h">@nikp3h</a>) e indica
        tu interés en entrar al sitio y proporciona tu nombre de agente y tu correo electrónico
        (<code>{{ app.user.email }}</code>) asociado para tu verificación.<br><br>

        Cuando te hayas contactado, los administradores validarán tu nombre y podrás acceder al sitio de los iluminados
        de Ecuador, Enlightened Elite Echelon of Ecuador, 4E para los panas.<br><br>

        In Jarvis we trust!
    </div>
{% endif %}

<p>{{ 'agents.in.database'|trans({'count': agents|length}) }}</p>

{# check for APP @todo ugly! #}
{% if '4emanager' != app.request.headers.get('User-Agent') %}
    <a href="https://play.google.com/store/apps/details?id=org.elkuku.a4emanager">
        <img src="{{ asset('images/ico/google-play-badge/128x128.png') }}" alt="4E App on Play Store">
    </a>
{% endif %}

templates/default/_search_box.html.twig
{% if is_granted('ROLE_INTRO_AGENT') %}
    <div class="card alert-success">
        <div class="card-body">
            {% if app.user.agent %}
                <b>{{ 'Import Stats'|trans }}</b>
                <form method="post" action="{{ path('stat_import') }}" class="form-inline" id="stats-upload">
                    <div class="input-group">
                        <textarea class="form-control" name="csv" id="csv" required="required"
                                  placeholder="{{ 'Prime export'|trans }}"></textarea>
                        <div class="input-group-append">
                            <button class="btn btn-outline-success" title="{{ 'Upload'|trans }}">
                                <span class="oi oi-cloud-upload"></span>
                            </button>
                        </div>
                    </div>
                    <input type="hidden" name="type" value="prime">
                    <!-- @todo FireBase token upload - to be filled by the app -->
                    <input type="hidden" id="FireBaseToken" name="fire_base_token" value="">
                </form>
            {% endif %}

            {% if is_granted('ROLE_AGENT') %}
                <b>{{ 'Search agent'|trans }}</b>
                <form method="post" action="{{ path('agent_index') }}" class="form-inline">
                    <div class="input-group">
                        <input type="text" id="searchAgent" required="required"
                               name="paginatorOptions[criteria][nickname]"
                               class="form-control" placeholder="{{ 'Agent nickname'|trans }}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-success" title="{{ 'Search'|trans }}">
                                <span class="oi oi-magnifying-glass"></span>
                            </button>
                        </div>
                    </div>
                </form>
            {% endif %}
            {% if app.user.agent %}
                {% if not app.user.agent.telegramId %}
                    <b>{{ 'Connect to Telegram'|trans }}</b>
                    <div>
                        <a class="btn btn-success" href="{{ path('tg_connect') }}" target="_blank">
                            {{ 'Connect to Telegram'|trans }}
                        </a>
                    </div>
                {% else %}
                    {% if not app.user.agent.hasNotifyUploadStats and not app.user.agent.hasNotifyStatsResult and not app.user.agent.hasNotifyEvents %}
                        <b>{{ 'Connect to Telegram'|trans }}</b>
                        <div class="alert-warning">
                            {{ 'You are connected to Telegram but have not enabled notifications. You may do this {link}.'
                            |trans({'link': '<a href="'~path('app_account')~'#telegram">'~'account.link.text'|trans~'</a>'})|raw }}
                        </div>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endif %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}4E{% endblock %}

{% block body %}

    <div class="card cite">
        <div class="card-body cite-body">
            <h5>
                <img src="{{ asset('images/tg-emojis/silhouette.png') }}" alt="silhouette" height="24px">
                {{ cite }}
            </h5>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-7">
            {% include 'default/_greeting.html.twig' %}
        </div>

        <div class="col-sm-5">
            {% include 'default/_search_box.html.twig' %}
        </div>
    </div>

    {% if is_granted('ROLE_AGENT') %}
        {% include 'default/_event_list.html.twig' %}
    {% endif %}
    {% if is_granted('ROLE_EDITOR') %}
        {% include 'default/_comment_list.html.twig' %}
    {% endif %}
{% endblock %}